//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.17 at 07:30:56 PM MSK 
//


package by.training.task4.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.example.org/Banks}deposit" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deposits"
})
@XmlRootElement(name = "Banks")
public class Banks {

    public Banks() {
        deposits = new ArrayList<>();
    }

    @XmlElementRef(name = "deposit", namespace = "http://www.example.org/Banks", type = JAXBElement.class)
    protected List<Deposit> deposits;

    /**
     * Gets the value of the deposit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deposit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeposit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Deposit }{@code >}
     * {@link JAXBElement }{@code <}{@link DepositForJuridicalPerson }{@code >}
     * {@link JAXBElement }{@code <}{@link DepositForNaturalPerson }{@code >}
     * 
     * 
     */
    public List<Deposit> getDeposits() {
        return deposits;
    }

    public void add(Deposit deposit) {
        deposits.add(deposit);
    }

    public void setDeposits(List<Deposit> deps) {
        deposits = deps;
    }

    @Override
    public String toString() {
        StringBuilder depositsToString = new StringBuilder();
        deposits.forEach(deposit -> depositsToString.append(deposit).append("\n"));
        return "Banks{\n" +
                "deposits=\n" + depositsToString +
                '}';
    }
}
