//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.17 at 07:30:56 PM MSK 
//


package by.training.task4.model;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DepositForJuridicalPerson complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DepositForJuridicalPerson">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/Banks}Deposit">
 *       &lt;all>
 *         &lt;element name="contactPerson" type="{http://www.example.org/Banks}SNP"/>
 *         &lt;element name="amount">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="10000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="companyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="companyLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DepositForJuridicalPerson", propOrder = {
    "contactPerson",
    "amount",
    "companyName",
    "companyLocation"
})
public class DepositForJuridicalPerson
    extends Deposit
{

    @XmlElement(required = true)
    protected SNP contactPerson = new SNP();
    @XmlElement(required = true)
    protected BigDecimal amount;
    @XmlElement(required = true)
    protected String companyName;
    @XmlElement(required = true)
    protected String companyLocation;

    /**
     * Gets the value of the contactPerson property.
     * 
     * @return
     *     possible object is
     *     {@link SNP }
     *     
     */
    public SNP getContactPerson() {
        return contactPerson;
    }

    /**
     * Sets the value of the contactPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link SNP }
     *     
     */
    public void setContactPerson(SNP value) {
        this.contactPerson = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmount(BigDecimal value) {
        this.amount = value;
    }

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the companyLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyLocation() {
        return companyLocation;
    }

    /**
     * Sets the value of the companyLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyLocation(String value) {
        this.companyLocation = value;
    }

    @Override
    public String toString() {
        return "DepositForJuridicalPerson{" +
                "contactPerson=" + contactPerson +
                ", amount=" + amount +
                ", companyName='" + companyName + '\'' +
                ", companyLocation='" + companyLocation + '\'' +
                ", name='" + name + '\'' +
                ", country='" + country + '\'' +
                ", profitability=" + profitability +
                ", duration=" + duration +
                ", dateOfDeposit=" + dateOfDeposit +
                ", type=" + type +
                ", accountID='" + accountID + '\'' +
                '}';
    }
}
