//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.17 at 07:30:56 PM MSK 
//


package by.training.task4.model;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import java.time.Duration;
import java.time.Period;


/**
 * <p>Java class for Deposit complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Deposit">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="country" type="{http://www.w3.org/2001/XMLSchema}string" default="Belarus" />
 *       &lt;attribute name="profitability" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="duration" type="{http://www.w3.org/2001/XMLSchema}duration" default="P1Y" />
 *       &lt;attribute name="dateOfDeposit" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="poste restante"/>
 *             &lt;enumeration value="urgent"/>
 *             &lt;enumeration value="settlement"/>
 *             &lt;enumeration value="accumulative"/>
 *             &lt;enumeration value="saving"/>
 *             &lt;enumeration value="metallic"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="accountID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Deposit")
@XmlSeeAlso({
    DepositForJuridicalPerson.class,
    DepositForNaturalPerson.class
})
public class Deposit {

    @XmlElement(name = "name", required = true)
    protected String name;
    @XmlElement(name = "country", defaultValue = "Belarus")
    protected String country;
    @XmlElement(name = "profitability", required = true)
    protected float profitability;
    @XmlElement(name = "duration")
    protected Period duration;
    @XmlElement(name = "dateOfDeposit", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOfDeposit;
    @XmlAttribute(name = "depositType", required = true)
    protected DepositType type;
    @XmlAttribute(name = "accountID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String accountID;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        if (country == null) {
            return "Belarus";
        } else {
            return country;
        }
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the profitability property.
     * 
     */
    public float getProfitability() {
        return profitability;
    }

    /**
     * Sets the value of the profitability property.
     * 
     */
    public void setProfitability(float value) {
        this.profitability = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Period getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setDuration(Period value) {
        this.duration = value;
    }

    /**
     * Gets the value of the dateOfDeposit property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfDeposit() {
        return dateOfDeposit;
    }

    /**
     * Sets the value of the dateOfDeposit property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfDeposit(XMLGregorianCalendar value) {
        this.dateOfDeposit = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public DepositType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(DepositType value) {
        this.type = value;
    }

    public void setType(String value) {
        this.type = DepositType.fromValue(value);
    }

    /**
     * Gets the value of the accountID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountID() {
        return accountID;
    }

    /**
     * Sets the value of the accountID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountID(String value) {
        this.accountID = value;
    }


}
