//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.17 at 07:30:56 PM MSK 
//


package by.training.task4.model;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DepositForNaturalPerson complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DepositForNaturalPerson">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/Banks}Deposit">
 *       &lt;all>
 *         &lt;element name="depositorName" type="{http://www.example.org/Banks}SNP"/>
 *         &lt;element name="amount">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DepositForNaturalPerson", propOrder = {
    "depositorName",
    "amount"
})
public class DepositForNaturalPerson
    extends Deposit
{

    @XmlElement(required = true)
    protected SNP depositorName = new SNP();
    @XmlElement(required = true)
    protected BigDecimal amount;

    /**
     * Gets the value of the depositorName property.
     * 
     * @return
     *     possible object is
     *     {@link SNP }
     *     
     */
    public SNP getDepositorName() {
        return depositorName;
    }

    /**
     * Sets the value of the depositorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link SNP }
     *     
     */
    public void setDepositorName(SNP value) {
        this.depositorName = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmount(BigDecimal value) {
        this.amount = value;
    }

    @Override
    public String toString() {
        return "DepositForNaturalPerson{" +
                "depositorName=" + depositorName +
                ", amount=" + amount +
                ", name='" + name + '\'' +
                ", country='" + country + '\'' +
                ", profitability=" + profitability +
                ", duration=" + duration +
                ", dateOfDeposit=" + dateOfDeposit +
                ", type=" + type +
                ", accountID='" + accountID + '\'' +
                '}';
    }
}
