CREATE DATABASE IF NOT EXISTS BEAUTY_SALOON DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE BEAUTY_SALOON;

CREATE TABLE PORTFOLIO (
	id INT AUTO_INCREMENT NOT NULL,
	id_Master INT NOT NULL UNIQUE,
	PRIMARY KEY (id, id_Master)
);

CREATE TABLE PHOTO (
	id_portfolio INT NOT NULL,
	id INT AUTO_INCREMENT PRIMARY KEY,
	photo LONGBLOB NOT NULL,
	filename VARCHAR(30) UNIQUE NOT NULL,
	filetype ENUM('.jpg', '.jpeg', '.png'),
	CONSTRAINT PHOTO_PORTFOLIO_FK FOREIGN KEY (id_portfolio) REFERENCES PORTFOLIO(id) ON DELETE CASCADE
);

CREATE TABLE PERSON (
	id INT AUTO_INCREMENT PRIMARY KEY,
	surname VARCHAR(20) NOT NULL,
	name VARCHAR(20) NOT NULL,
	email VARCHAR(30) NOT NULL,
	phone VARCHAR(20),
	passwordHash VARCHAR (30) NOT NULL,
	role ENUM('admin', 'client', 'master') NOT NULL,
	UNIQUE (email, role)
);

CREATE TABLE SPECIALIZATION (
	id INT AUTO_INCREMENT PRIMARY KEY,
	specialization VARCHAR(20) NOT NULL
);

CREATE TABLE BEAUTY_MASTER (
	id INT PRIMARY KEY,
	id_portfolio INT,
	experience TINYINT(2) UNSIGNED NOT NULL,
	employment_date DATE NOT NULL,
	status ENUM('working', 'fired'),
	CONSTRAINT MASTER_PERSON_FK FOREIGN KEY (id) REFERENCES PERSON(id) ON DELETE CASCADE,
	CONSTRAINT MASTER_PORTFOLIO_FK FOREIGN KEY (id_portfolio) REFERENCES PORTFOLIO(id) ON DELETE SET NULL
);

ALTER TABLE PORTFOLIO
ADD CONSTRAINT PORTFOLIO_MASTER_FK FOREIGN KEY (id_Master) REFERENCES BEAUTY_MASTER(id) ON DELETE CASCADE;

CREATE TABLE MASTER_SPECIALIZATION (
	id_Master INT NOT NULL,
	id_Specialization INT NOT NULL,
	CONSTRAINT SPEC_MASTER_FK FOREIGN KEY (id_Master) REFERENCES BEAUTY_MASTER(id) ON DELETE CASCADE,
	FOREIGN KEY SPEC_SPEC_FK (id_Specialization) REFERENCES SPECIALIZATION(id) ON DELETE CASCADE,
	PRIMARY KEY (id_Master, id_Specialization)
);

CREATE TABLE BEAUTY_CLIENT (
	id INT PRIMARY KEY,
	CONSTRAINT CLIENT_PERSON_FK FOREIGN KEY (id) REFERENCES PERSON(id) ON DELETE CASCADE
);

CREATE TABLE SERVICE (
	id INT AUTO_INCREMENT,
	id_Specialization INT NOT NULL,
	service VARCHAR(100) NOT NULL,
	cost DECIMAL(10, 4) NOT NULL,
	duration INT UNSIGNED NOT NULL,
	PRIMARY KEY (id, service),
	CONSTRAINT SERVICE_SPEC_FK FOREIGN KEY (id_Specialization) REFERENCES SPECIALIZATION(id) ON DELETE CASCADE
);

CREATE TABLE MASTER_SERVICE (
	id_Master INT NOT NULL,
	id_Service INT NOT NULL,
	CONSTRAINT SERVICE_MASTER_FK FOREIGN KEY (id_Master) REFERENCES BEAUTY_MASTER(id) ON DELETE CASCADE,
	CONSTRAINT SERVIVE_SERVICE_FK FOREIGN KEY (id_Service) REFERENCES SERVICE(id) ON DELETE CASCADE,
	PRIMARY KEY (id_Master, id_Service)
);

CREATE TABLE PROMOCODE (
	id INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(10) NOT NULL,
	discount TINYINT(3) NOT NULL
);

CREATE TABLE SERVICE_PROMOCODE (
	id_Service INT NOT NULL,
	id_Promocode INT NOT NULL,
	CONSTRAINT SERV_PROMO_SERVICE_FK FOREIGN KEY (id_Service) REFERENCES SERVICE(id) ON DELETE CASCADE,
	CONSTRAINT SERV_PROMO_PROMOCODE_FK FOREIGN KEY (id_Promocode) REFERENCES PROMOCODE(id) ON DELETE CASCADE,
	PRIMARY KEY (id_Service, id_Promocode)
);

CREATE TABLE REVIEW (
	id INT AUTO_INCREMENT PRIMARY KEY,
	id_Master INT,
	id_Client INT, 
	id_Service INT NOT NULL,
	review TEXT NOT NULL,
	CONSTRAINT REVIEW_MASTER_FK FOREIGN KEY (id_Master) REFERENCES BEAUTY_MASTER(id) ON DELETE SET NULL,
	CONSTRAINT REVIEW_CLIENT_FK FOREIGN KEY (id_Client) REFERENCES BEAUTY_CLIENT(id) ON DELETE SET NULL,
	CONSTRAINT REVIEW_SERVICE_FK FOREIGN KEY (id_Service) REFERENCES SERVICE(id) ON DELETE CASCADE
);

CREATE TABLE SESSION (
	id INT AUTO_INCREMENT PRIMARY KEY,
	id_Client INT NOT NULL,
	id_Master INT NOT NULL,
  id_Service INT NOT NULL,
	session_date DATE NOT NULL,
	session_time TIME NOT NULL,
	CONSTRAINT SESSION_CLIENT_FK FOREIGN KEY (id_Client) REFERENCES BEAUTY_CLIENT(id) ON DELETE CASCADE,
	CONSTRAINT SESSION_MASTER_FK FOREIGN KEY (id_Master) REFERENCES BEAUTY_MASTER(id) ON DELETE CASCADE,
    CONSTRAINT SESSION_SERVICE_FK FOREIGN KEY (id_Service) REFERENCES SERVICE(id) ON DELETE CASCADE
);

INSERT INTO SPECIALIZATION (specialization) VALUES
('make-up'),
('hairdressing'),
('nails'),
('hairhealth'),
('hairstyle'),
('epilation'),
('eyebrows'),
('cosmetology'),
('mehendi');

/*
CREATE USER 'appUser'@'localhost' IDENTIFIED BY 'IVr69LG8*l';

GRANT SELECT, UPDATE, INSERT, DELETE ON BEAUTY_SALOON.* TO 'appUser'@'localhost';
FLUSH privileges;

GRANT SELECT, INSERT, UPDATE, DELETE, FILE ON *.* TO 'appUser'@'localhost' IDENTIFIED BY PASSWORD '*7717C61818E3C1EE324D272EFE28CBCA2CADA772';

GRANT SELECT, INSERT, UPDATE, DELETE ON `beauty_saloon`.* TO 'appUser'@'localhost';
*/